on: push
name: Build APK
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.19.3'
    - run: flutter pub get
    # test
    - run: flutter build apk --split-per-abi --no-tree-shake-icons --obfuscate --split-debug-info=./obfuscate
      if: ${{ contains(github.event.head_commit.message, 'Update')}}
    - name: Push APK to Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/debug/*.apk"
        prerelease: true
        tag: 'v0.2.0'
